name: Deploy to PROD
on:
  push:
    branches:
      - master
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install serverless globally
        run: npm install -g serverless

      - name: Install NPM dependencies
        run: npm install

      - name: Install dependencies for layer
        run: npm run layer-deps-install

      - name: Serverless AWS authentication
        run: serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile vighnesh153

      - name: Deploy Lambda functions
        run: serverless deploy --stage prod
